# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-12 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_orders_isdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='suser',
            new_name='susers',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='buy_user',
            new_name='buy_users',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='sale_user',
            new_name='sale_users',
        ),
    ]
