# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-12 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='uidentity',
            new_name='uid',
        ),
    ]
