# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-12 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_carinfo_isdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='logo_brand',
            new_name='Logo_brand',
        ),
        migrations.RenameField(
            model_name='carinfo',
            old_name='ctitle',
            new_name='c_title',
        ),
    ]
